apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonApp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      tag: pythonapp
  template:
    metadata:
      labels:
        tag: pythonapp
    spec:
      containers:
        - name: pythonApp
          image: mohamedsalah/python-app:latest
          ports:
            - containerPort: 8000
