apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    tag: pythonapp
